// cityOptions.js
export const cityOptions = [
    { value: 'bangalore' },
    { value: 'hyderabad' },
    { value: 'chennai' },
    { value: 'pune' },
    { value: 'mumbai' },
    { value: 'noida' },
    { value: 'gurgaon' },
    { value: 'kolkata' },
    { value: 'ahmedabad' },
    { value: 'chandigarh' },
    { value: 'jaipur' },
    { value: 'coimbatore' },
];

export const jobNicheOptions = [
    { value: 'frontend developer', label: 'Frontend Developer' },
    { value: 'backend developer', label: 'Backend Developer' },
    { value: 'full stack developer', label: 'Full Stack Developer' },
    { value: 'mobile app developer', label: 'Mobile App Developer' },
    { value: 'software engineer', label: 'Software Engineer' },
    { value: 'devops engineer', label: 'DevOps Engineer' },
    { value: 'data scientist', label: 'Data Scientist' },
    { value: 'data analyst', label: 'Data Analyst' },
    { value: 'data engineer', label: 'Data Engineer' },
    { value: 'bi developer', label: 'Business Intelligence (BI) Developer' },
    { value: 'machine learning engineer', label: 'Machine Learning Engineer' },
    { value: 'cybersecurity analyst', label: 'Cybersecurity Analyst' },
    { value: 'penetration tester', label: 'Penetration Tester (Ethical Hacker)' },
    { value: 'security engineer', label: 'Security Engineer' },
    { value: 'information security manager', label: 'Information Security Manager' },
    { value: 'cloud architect', label: 'Cloud Architect' },
    { value: 'cloud engineer', label: 'Cloud Engineer' },
    { value: 'cloud consultant', label: 'Cloud Consultant' },
    { value: 'network administrator', label: 'Network Administrator' },
    { value: 'network engineer', label: 'Network Engineer' },
    { value: 'systems administrator', label: 'Systems Administrator' },
    { value: 'it support specialist', label: 'IT Support Specialist' },
    { value: 'it project manager', label: 'IT Project Manager' },
    { value: 'it service manager', label: 'IT Service Manager' },
    { value: 'scrum master', label: 'Scrum Master' },
    { value: 'database administrator', label: 'Database Administrator (DBA)' },
    { value: 'database developer', label: 'Database Developer' },
    { value: 'database architect', label: 'Database Architect' },
    { value: 'ai research scientist', label: 'AI Research Scientist' },
    { value: 'robotics engineer', label: 'Robotics Engineer' },
    { value: 'nlp specialist', label: 'Natural Language Processing (NLP) Specialist' },
    { value: 'ux designer', label: 'UX Designer' },
    { value: 'ui designer', label: 'UI Designer' },
    { value: 'interaction designer', label: 'Interaction Designer' },
    { value: 'web developer', label: 'Web Developer' },
    { value: 'web designer', label: 'Web Designer' },
    { value: 'ecommerce specialist', label: 'E-commerce Specialist' },
    { value: 'systems analyst', label: 'Systems Analyst' },
    { value: 'business analyst', label: 'Business Analyst' },
    { value: 'it consultant', label: 'IT Consultant' }
];


export const Joblist = [
    {
        id: 1,
        title: "Sr. MERN Stack Developer",
        jobType: "Full-time",
        location: "Indore",
        companyName: "Demo Company Name",
        introduction: "It is demo introduction of Demo Company Name.",
        responsibilities: "Responsibilities include developing and maintaining web applications using the MERN stack.",
        qualifications: "5+ years of experience with MongoDB, Express.js, React, and Node.js.",
        salary: 60000,
        jobNiche: "Web development",
        offer: "Offer1",
        hiringMultipleCandidates: "Yes",
        personalWebsiteTitle: "My Portfolio",
        personalWebsiteUrl: "https://creativeshowcasehub.netlify.app/"
      },
      {
        id: 2,
        title: "Junior Frontend Developer",
        jobType: "Part-time",
        location: "Bangalore",
        companyName: "Tech Innovators Inc.",
        introduction: "Join our team as a Junior Frontend Developer and work on exciting projects.",
        responsibilities: "Develop and maintain user interfaces for web applications.",
        qualifications: "Bachelor's degree in Computer Science or related field. Experience with HTML, CSS, and JavaScript.",
        salary: 40000,
        jobNiche: "Frontend development",
        offer: "Offer2",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "My Tech Blog",
        personalWebsiteUrl: "https://techblog.example.com/"
      },
      {
        id: 3,
        title: "UX/UI Designer",
        jobType: "Contract",
        location: "Remote",
        companyName: "Creative Solutions Ltd.",
        introduction: "Creative Solutions Ltd. is looking for a talented UX/UI Designer to enhance user experience.",
        responsibilities: "Design user interfaces and create wireframes and prototypes.",
        qualifications: "Proven experience in UX/UI design with a strong portfolio.",
        salary: 50000,
        jobNiche: "Design",
        offer: "Offer3",
        hiringMultipleCandidates: "Yes",
        personalWebsiteTitle: "Design Showcase",
        personalWebsiteUrl: "https://designshowcase.example.com/"
      },
      {
        id: 4,
        title: "Backend Developer",
        jobType: "Full-time",
        location: "Mumbai",
        companyName: "CodeMasters",
        introduction: "CodeMasters is seeking a Backend Developer with expertise in building scalable APIs.",
        responsibilities: "Develop and maintain backend services and APIs.",
        qualifications: "3+ years of experience with Node.js and database management.",
        salary: 70000,
        jobNiche: "Backend development",
        offer: "Offer4",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "Backend Insights",
        personalWebsiteUrl: "https://backendinsights.example.com/"
      },
      {
        id: 5,
        title: "Data Scientist",
        jobType: "Full-time",
        location: "Delhi",
        companyName: "DataWizards",
        introduction: "DataWizards is looking for a Data Scientist to analyze and interpret complex data sets.",
        responsibilities: "Analyze data to provide actionable insights and build predictive models.",
        qualifications: "Experience with Python, R, and machine learning algorithms.",
        salary: 80000,
        jobNiche: "Data Science",
        offer: "Offer5",
        hiringMultipleCandidates: "Yes",
        personalWebsiteTitle: "Data Science Portfolio",
        personalWebsiteUrl: "https://datascienceportfolio.example.com/"
      },
      {
        id: 6,
        title: "DevOps Engineer",
        jobType: "Full-time",
        location: "Hyderabad",
        companyName: "CloudTech Solutions",
        introduction: "Join CloudTech Solutions as a DevOps Engineer to enhance our CI/CD pipelines.",
        responsibilities: "Implement and manage CI/CD pipelines and infrastructure automation.",
        qualifications: "Experience with Docker, Kubernetes, and cloud platforms.",
        salary: 75000,
        jobNiche: "DevOps",
        offer: "Offer6",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "DevOps Hub",
        personalWebsiteUrl: "https://devopshub.example.com/"
      },
      {
        id: 7,
        title: "Mobile App Developer",
        jobType: "Part-time",
        location: "Chennai",
        companyName: "AppMasters",
        introduction: "AppMasters is seeking a Mobile App Developer to create and maintain mobile applications.",
        responsibilities: "Develop and optimize mobile applications for iOS and Android platforms.",
        qualifications: "Experience with React Native or Flutter.",
        salary: 50000,
        jobNiche: "Mobile Development",
        offer: "Offer7",
        hiringMultipleCandidates: "Yes",
        personalWebsiteTitle: "Mobile Development Portfolio",
        personalWebsiteUrl: "https://mobiledportfolio.example.com/"
      },
      {
        id: 8,
        title: "Technical Writer",
        jobType: "Contract",
        location: "Remote",
        companyName: "TechDocs",
        introduction: "TechDocs is looking for a Technical Writer to create detailed documentation for our products.",
        responsibilities: "Write and edit user manuals, API documentation, and technical guides.",
        qualifications: "Excellent writing skills and experience in technical documentation.",
        salary: 45000,
        jobNiche: "Technical Writing",
        offer: "Offer8",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "Technical Writing Samples",
        personalWebsiteUrl: "https://techwritingsamples.example.com/"
      },
      {
        id: 9,
        title: "Graphic Designer",
        jobType: "Freelance",
        location: "Kolkata",
        companyName: "DesignStudio",
        introduction: "DesignStudio is seeking a freelance Graphic Designer for various design projects.",
        responsibilities: "Create visual designs for digital and print media.",
        qualifications: "Proficiency in Adobe Creative Suite and design principles.",
        salary: 35000,
        jobNiche: "Graphic Design",
        offer: "Offer9",
        hiringMultipleCandidates: "Yes",
        personalWebsiteTitle: "Graphic Design Portfolio",
        personalWebsiteUrl: "https://graphicdesignportfolio.example.com/"
      },
      {
        id: 10,
        title: "Product Manager",
        jobType: "Full-time",
        location: "Pune",
        companyName: "InnovateCorp",
        introduction: "InnovateCorp is looking for a Product Manager to drive product strategy and development.",
        responsibilities: "Define product vision, roadmap, and strategy. Collaborate with cross-functional teams.",
        qualifications: "Experience in product management and project management skills.",
        salary: 90000,
        jobNiche: "Product Management",
        offer: "Offer10",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "Product Management Insights",
        personalWebsiteUrl: "https://productmanagementinsights.example.com/"
      },
      {
        id: 11,
        title: "Sales Executive",
        jobType: "Full-time",
        location: "Ahmedabad",
        companyName: "SalesPro Ltd.",
        introduction: "SalesPro Ltd. is hiring a Sales Executive to drive sales and manage client relationships.",
        responsibilities: "Develop sales strategies, meet sales targets, and maintain client relationships.",
        qualifications: "Experience in sales and customer service.",
        salary: 40000,
        jobNiche: "Sales",
        offer: "Offer11",
        hiringMultipleCandidates: "Yes",
        personalWebsiteTitle: "Sales Portfolio",
        personalWebsiteUrl: "https://salesportfolio.example.com/"
      },
      {
        id: 12,
        title: "Cybersecurity Analyst",
        jobType: "Full-time",
        location: "Noida",
        companyName: "SecureTech",
        introduction: "SecureTech is seeking a Cybersecurity Analyst to protect our IT infrastructure.",
        responsibilities: "Monitor and analyze security incidents, implement security measures.",
        qualifications: "Experience with security tools and protocols.",
        salary: 70000,
        jobNiche: "Cybersecurity",
        offer: "Offer12",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "Cybersecurity Portfolio",
        personalWebsiteUrl: "https://cybersecurityportfolio.example.com/"
      },
      {
        id: 13,
        title: "AI Research Scientist",
        jobType: "Full-time",
        location: "Gurgaon",
        companyName: "AI Innovations",
        introduction: "AI Innovations is looking for an AI Research Scientist to lead cutting-edge AI research projects.",
        responsibilities: "Conduct research on AI algorithms and models, publish research papers.",
        qualifications: "Ph.D. in Computer Science or related field, with a focus on AI.",
        salary: 100000,
        jobNiche: "Artificial Intelligence",
        offer: "Offer13",
        hiringMultipleCandidates: "No",
        personalWebsiteTitle: "AI Research Portfolio",
        personalWebsiteUrl: "https://airesearchportfolio.example.com/"
      }
  ];
  
  export const Qualifications=[
    { "id": 1, "qualification": "Bachelor of Arts (BA)" },
    { "id": 2, "qualification": "Bachelor of Science (BSc)" },
    { "id": 3, "qualification": "Bachelor of Commerce (BCom)" },
    { "id": 4, "qualification": "Bachelor of Engineering (BE) / Bachelor of Technology (BTech)" },
    { "id": 5, "qualification": "Bachelor of Medicine and Bachelor of Surgery (MBBS)" },
    { "id": 6, "qualification": "Bachelor of Pharmacy (BPharm)" },
    { "id": 7, "qualification": "Bachelor of Fine Arts (BFA)" },
    { "id": 8, "qualification": "Bachelor of Business Administration (BBA)" },
    { "id": 9, "qualification": "Bachelor of Design (BDes)" },
    { "id": 10, "qualification": "Bachelor of Hotel Management (BHM)" },
    { "id": 11, "qualification": "Master of Arts (MA)" },
    { "id": 12, "qualification": "Master of Science (MSc)" },
    { "id": 13, "qualification": "Master of Commerce (MCom)" },
    { "id": 14, "qualification": "Master of Business Administration (MBA)" },
    { "id": 15, "qualification": "Master of Technology (MTech) / Master of Engineering (ME)" },
    { "id": 16, "qualification": "Master of Computer Applications (MCA)" },
    { "id": 17, "qualification": "Master of Fine Arts (MFA)" },
    { "id": 18, "qualification": "Master of Design (MDes)" },
    { "id": 19, "qualification": "Master of Pharmacy (MPharm)" },
    { "id": 20, "qualification": "Master of Laws (LLM)" }
]
